AllCops:
  Include:
    - '**/metadata.rb'
    - '**/Gemfile'
    - attributes/**/*
    - recipes/**/*.rb
    - spec/**/*.rb
    - test/**/*.rb
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/MixinUsage:
  Exclude:
    - providers/**/*.rb

Encoding:
  Exclude:
    - '**/metadata.rb'
    - Gemfile
    - Rakefile

Naming/FileName:
  Enabled: false

NumericLiterals:
  Enabled: false

LineLength:
  Enabled: false

WordArray:
  MinSize: 3

Metrics/AbcSize:
  Enabled: false
