AllCops:
  Include:
    - '**/metadata.rb'
    - '**/Gemfile'
    - attributes/**/*
    - recipes/**/*.rb
    - spec/**/*.rb
    - test/**/*.rb
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

Encoding:
  Exclude:
    - '**/metadata.rb'
    - Gemfile

NumericLiterals:
  Enabled: false

LineLength:
  Enabled: false

WordArray:
  MinSize: 3

Metrics/AbcSize:
  Enabled: false
